### ISSUE TITLE
ollama running local: Error condensing thoughts: 'NoneType' object has no attribute 'request'

### ISSUE THREAD

**Issue by ivanjrt** [OpenDevin/OpenDevin#1034]
when opening the app `make run` then I start to type in the prompt., then I get error <br/>
**"Error condensing thoughts: 'NoneType' object has no attribute 'request'"**

#### Setup and configuration
**Current version**:
```bash
commit 9fd95cc35fb1cb05ee72412b6188debda44d25d5 (HEAD -> main, origin/main, origin/HEAD)
Author: Redrum624 <lauzon624@gmail.com>
Date:   Thu Apr 11 22:12:23 2024 -0400
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_API_KEY="anything"
LLM_MODEL="ollama/mistral:latest"
LLM_EMBEDDING_MODEL="mistral"
LLM_BASE_URL="http://localhost:11434"
WORKSPACE_DIR="./workspace"
SANDBOX_TYPE="exec"
```
_I have removed the `LLM_API_KEY` to see if this will give me a different output but same error,<br/>
I have added `1111111111` but same error, <br/>
I have added the key that shows in `C:\Users\me\AppData\Local\Ollama` > server , after the `ssh-ed25519 `, <br/>_

**My model and agent** (you can see these settings in the UI):
![image](https://github.com/OpenDevin/OpenDevin/assets/44326428/f78770c4-d29d-4120-a1b9-f65a6c5a1163)<br/>
**Commands I ran to install and run OpenDevin**:
```
make run
```

**Steps to Reproduce**:
0. WSL, Windows 11, python 3.11
1. just add that configuration i have above for the toml file

**Logs, error messages, and screenshots**:
![image](https://github.com/OpenDevin/OpenDevin/assets/44326428/0f6f0089-d671-407a-a145-c53b70c87805)<br/>

![image](https://github.com/OpenDevin/OpenDevin/assets/44326428/a192557d-8374-4866-a082-fd7e897a5a86)<br/>
