### ISSUE TITLE
Workspace directory not updating correctly from UI

### ISSUE THREAD

**Issue by akhilvc10** [OpenDevin/OpenDevin#1090]
## Description

When I change the workspace directory in the OpenDevin UI, the actual working directory does not update. The UI or the config.toml file does not show the correct working directory.

## Setup and Configuration

**Current version**:

```bash
Author: Boxuan Li <liboxuan@connect.hku.hk>
Date:   Sat Apr 13 21:51:17 2024 -0700

    Revamp Exception handling (#1080)
```

**My config.toml and environment vars**

```toml
LLM_MODEL="gpt-4-0125-preview"
LLM_API_KEY="api_key"
LLM_EMBEDDING_MODEL="openai"
WORKSPACE_DIR="./workspace"

```

**My model and agent** 

* Model: gpt-4-turbo-2024-04-09
* Agent: MonologueAgent  

## Steps to Reproduce

1. Open the OpenDevin UI
2. Change the Workspace directory to a different value (e.g., "working_directory-2")
3. Observe that the actual working directory does not change

## Additional Context

This issue is preventing me from properly managing my workspace directory within the OpenDevin application.
