### ISSUE TITLE
Error creating controller: Failed to setup devin user: b'Cannot open audit interface - aborting.\n'

### ISSUE THREAD

**Issue by AndrewTsai0406** [OpenDevin/OpenDevin#1110]
#### Describe the bug

While excuting `make run`, an error occur because the container failed to excute. Command used for `self.container.exec_run => ['/bin/bash', '-c', 'useradd --shell /bin/bash -u 895651443 -o -c "" -m devin']`

[Edited] I'm on a Ubuntu 20.04.6 LTS

Please help~ Thank you.

#### Setup and configuration
**Current version**:

```bash
commit 98d019b825bdf6408bcc70c67ce31d9d7fe1a417 (HEAD -> main, origin/main, origin/HEAD)
Author: Tunay Engin <160699323+etunay-mufin@users.noreply.github.com>
Date:   Mon Apr 15 06:07:59 2024 +0300

    Adding: Turkish language (#1102)
    
    * Adding: Turkish language
    
    * Add space
    
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml

LLM_MODEL="gpt-3.5-turbo-16k"
LLM_API_KEY=""
LLM_EMBEDDING_MODEL="azureopenai"
LLM_BASE_URL="https://scusmsadrcdasopenaijapan.openai.azure.com/"
LLM_DEPLOYMENT_NAME="gpt-35-turbo-16k"
LLM_API_VERSION="0613"
WORKSPACE_DIR="./workspace"
SANDBOX_TYPE="exec"
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
poetry shell
poetry install --no-root
```

**Steps to Reproduce**:
1. make build
2. make set-config
3. make run

**Logs, error messages, and screenshots**:
![image](https://github.com/OpenDevin/OpenDevin/assets/33444357/20f6366d-8c93-4c63-b3aa-4c871e4cc986)
