### ISSUE TITLE
The docker container exits with: "opendevin-1 exited with code 132" as soon as i load the webGUI

### ISSUE THREAD

**Issue by baarsnet** [OpenDevin/OpenDevin#1246]
Has anybody an Idea why my opendevin container stops as soon as i try to open the WebGUI

#### Describe the bug
When i run OpenDevin container i get "**opendevin-1 exited with code 132**" as soon as i open the page.

This is the error

```
Attaching to opendevin-1
opendevin-1  | INFO:     Started server process [1]
opendevin-1  | INFO:     Waiting for application startup.
opendevin-1  | INFO:     Application startup complete.
opendevin-1  | INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
opendevin-1  | INFO:     10.0.10.130:61767 - "GET / HTTP/1.1" 307 Temporary Redirect
opendevin-1  | INFO:     10.0.10.130:61767 - "GET /index.html HTTP/1.1" 200 OK
opendevin-1  | INFO:     10.0.10.130:61767 - "GET /assets/index-_KDl21L3.js HTTP/1.1" 200 OK
opendevin-1  | INFO:     10.0.10.130:61768 - "GET /assets/index-CRo1D-kC.css HTTP/1.1" 200 OK
opendevin-1  | INFO:     ('10.0.10.130', 61770) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiI2NzQ5MTE1OS04MzkzLTRjOTgtODk4Zi00ODFhYTM0Nzg5YzgifQ.ihMAmU9bXs7caQKrXqD1T1LYUZXUb9-qiKxb6h8NGTw" [accepted]
opendevin-1  | INFO:     connection open
opendevin-1  | Starting loop_recv for sid: 67491159-8393-4c98-898f-481aa34789c8
opendevin-1  | INFO:     10.0.10.130:61767 - "GET /locales/en/translation.json HTTP/1.1" 200 OK
opendevin-1  | INFO:     10.0.10.130:61767 - "GET /api/refresh-files HTTP/1.1" 200 OK
opendevin-1  | 23:49:20 - opendevin:INFO: agent.py:145 - Creating agent MonologueAgent using LLM ollama/llama2
opendevin-1  | 23:49:20 - opendevin:INFO: llm.py:27 - Initializing LLM with model: ollama/llama2
opendevin-1 exited with code 132

```

And this is my docker-compose file that i run

version: '3.8'

```
services:
  opendevin:
    image: ghcr.io/opendevin/opendevin:latest
    environment:
      LLM_API_KEY: "ollama"
      LLM_BASE_URL: "http://192.168.200.10:11434"
      LLM_MODEL: "ollama/llama2:latest"
      LLM_EMBEDDING_MODEL: "llama2"
      WORKSPACE_MOUNT_PATH: "/root/opendevin_docker/workspace"
      WORKSPACE_DIR: "/root/workspace_base"
    volumes:
      - /root/opendevin_docker/logs:/app/logs
      - /root/opendevin_docker/workspace:/opt/workspace_base
      - /run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
```

This is the content of my opendevin_2024-04-19.log

```
23:49:20 - opendevin:INFO: agent.py:145 - Creating agent MonologueAgent using LLM ollama/llama2
23:49:20 - opendevin:INFO: llm.py:27 - Initializing LLM with model: ollama/llama2
```

**Commands I ran to install and run OpenDevin**:
docker-compose up
**Steps to Reproduce**:
Run the dockercompose.
