### ISSUE TITLE
Refined `ghcr.yml` for Secure and Efficient Docker Operations

### ISSUE THREAD

**Issue by Umpire2018** [OpenDevin/OpenDevin#1681]
**Description**

We currently have a GitHub Actions setup that manages the build and push process for Docker images. This setup is triggered by both direct pushes and pull requests from forks. However, there are significant challenges related to security, efficiency, and complexity due to the way we handle different triggers. Specifically, our current workflow does not sufficiently differentiate between operations that are safe for PRs from forks and those that should only occur in trusted scenarios.

**Current Issues**

- Security Risks: The existing workflow indiscriminately handles ghcr.io logins and image pushes regardless of the origin of the PR, potentially exposing sensitive credentials during builds from forks.
- Inefficiency in Caching: Our current caching mechanisms do not differentiate between fork-based PRs and main repository operations, potentially leading to increased build times and cache pollution.
- Workflow Complexity: The logic for determining when to push images and manage caches is complex and difficult to maintain, particularly as we scale up the number of Docker images or adjust workflow conditions. **There are too much builds!**

<img width="326" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/138990495/99af39a8-7000-4e14-b31c-8c1425a4207d">

**Proposed Enhancements**

1. Enhanced Security Measures:

Conditional Execution: Implement steps that conditionally perform ghcr.io logins and image pushes. Specifically, these actions should only execute for non-fork PRs and direct repository pushes to prevent unauthorized access to ghcr.io credentials during the CI/CD process triggered by forks.

2. Optimized Caching Strategy:

Differentiated Caching: Utilize a more nuanced caching approach that varies based on the origin of the PR (fork vs. main repo). This strategy aims to reduce build times and prevent the risk of cache corruption from untrusted sources.

**Implementation of Workflow Changes**

```yml
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork }}
          tags: ${{ github.repository_owner }}/image:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64
```

Looks like there will be a lot of changes if we implement this change so I'm just giving a suggestion.
