### ISSUE TITLE
SANDBOX_USER_ID,i use dockerdesktop on windows 

### ISSUE THREAD

**Issue by ruanjianlun** [OpenDevin/OpenDevin#1903]
```
version: '3.8'

services:
  opendevin:
    image: ghcr.io/opendevin/opendevin:0.5
    pull_policy: always
    container_name: opendevin_container
    environment:
    # can i get SANDBOX_USER_ID from? 
      - SANDBOX_USER_ID=1000
      - LLM_API_KEY=ollama
      - LLM_MODEL="ollama/codellama:7b"
      - LLM_EMBEDDING_MODEL="local"
      - LLM_BASE_URL=http://host.docker.internal:11434
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE}
    volumes:
      - ${WORKSPACE_BASE}:/opt/workspace_base
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
```
