### ISSUE TITLE
[Bug]: CodeCov shows "failed" when it's still working

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#2369]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

For most CI actions, when they are working they display a yellow circle indicating that they're still working. However, for codecov, when it is still working it shows a red x for "failed" until it finishes, and when it finishes it converts to the green check for "passing". This is a bit annoying because it makes it seem like tests have failed when indeed they're still just working.

### Current OpenDevin version

```bash
main
```

### Installation and Configuration

```bash
NA
```

**Comment by neubig** [comment]
@li-boxuan would you have any ideas about how we might fix this?

**Comment by tobitege** [comment]
## Here's Gemini's suggestion:

The issue stems from GitHub Actions marking a job as failed when it encounters a running CodeCov upload. Since the CodeCov upload often occurs while tests are still running, this leads to the "red cross" even though the tests might still be in progress.

To resolve this, you can leverage the `fail_ci_if_error` option provided by the `codecov/codecov-action@v4`. By setting it to `false`, CodeCov will not mark the job as failed if an error occurs during the upload process, allowing the tests to complete and determine the final status of the job.

Here's the improved GitHub Actions workflow:

```yaml
name: Run Unit Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'frontend/**'
      - 'docs/**'
      - 'evaluation/**'
  pull_request:

env:
  PERSIST_SANDBOX : "false"

jobs:
  test-on-macos:
    name: Test on macOS
    runs-on: macos-13
    env:
      INSTALL_DOCKER: "1" # Set to '0' to skip Docker installation
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry via pipx
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install Python dependencies using Poetry
        run: poetry install

      - name: Install & Start Docker
        if: env.INSTALL_DOCKER == '1'
        run: |
          brew install colima docker
          colima start

          # For testcontainers to find the Colima socket
          # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock

      - name: Build Environment
        run: make build

      - name: Run Tests
        run: poetry run pytest --forked --cov=agenthub --cov=opendevin --cov-report=xml ./tests/unit -k "not test_sandbox"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false # This line has been added
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  test-on-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    env:
      INSTALL_DOCKER: "0" # Set to '0' to skip Docker installation
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry via pipx
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install Python dependencies using Poetry
        run: poetry install --without evaluation

      - name: Build Environment
        run: make build

      - name: Run Tests
        run: poetry run pytest --forked --cov=agenthub --cov=opendevin --cov-report=xml ./tests/unit -k "not test_sandbox"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false # This line has been added
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-for-sandbox:
    name: Test for Sandbox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry via pipx
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install Python dependencies using Poetry
        run: poetry install

      - name: Build Environment
        run: make build

      - name: Run Integration Test for Sandbox
        run: |
          poetry run pytest --cov=agenthub --cov=opendevin --cov-report=xml -s ./tests/unit/test_sandbox.py

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false # This line has been added
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```

By adding `fail_ci_if_error: false` within the `with` block of each `codecov/codecov-action@v4` step, the CodeCov upload will no longer prematurely mark the job as failed, allowing the "yellow spinner" to appear correctly while the tests are running.

**Comment by tobitege** [comment]
And check if actions could make use of updates to their latest stable versions (actions/checkout@v4, actions/setup-python@v5, codecov/codecov-action@v4).

**Comment by SmartManoj** [comment]
Should add more tests. Till that disabling that test would be better as it's annoying.

**Comment by li-boxuan** [comment]
`fail_ci_if_error = false` is the default behavior.

`wait_for_ci` might do the trick... let me try

**Comment by li-boxuan** [comment]
No I don't think there's a fix according to https://community.codecov.com/t/github-status-notification-isnt-delayed-should-wait-all-ci-jobs-to-finish/3708/18, unless we explicitly set `after_n_builds` (I don't think we should do it). So this issue seems going nowhere.

**Comment by SmartManoj** [comment]
Value updated after each test? https://github.com/OpenDevin/OpenDevin/pull/2366
![image](https://github.com/OpenDevin/OpenDevin/assets/7231077/2cfd03ef-36a5-443c-9df8-78615b1d96dc)
![image](https://github.com/OpenDevin/OpenDevin/assets/7231077/7a2f29b2-e118-4f7c-91b2-1bacf0a39943)

**Comment by SmartManoj** [comment]
> Here's Gemini's suggestion (this is the unit tests one. Edit: below is "as is", I didn't review the changes):

@tobitege Also, ask it to generate a TLDR version too.

**Comment by tobitege** [comment]
Hmm... got its (llm) response down to this:
```
- name: Upload coverage to Codecov
         uses: codecov/codecov-action@v4
         env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+        continue-on-error: true

       - name: Upload coverage to Codecov
         uses: codecov/codecov-action@v4
         env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+        continue-on-error: true

       - name: Upload coverage to Codecov
         uses: codecov/codecov-action@v4
         env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+        continue-on-error: true
```
_This diff highlights the three places where the `continue-on-error: true` line was added under the Codecov upload steps in the test-on-macos, test-on-linux, and test-for-sandbox jobs._
