### ISSUE TITLE
Multiple introduction messages sent on settings update

### ISSUE THREAD

**Issue by HosseyNJF** [OpenDevin/OpenDevin#549]
#### Describe the bug
When changing the settings from the UI, you'll see three messages saying `Hello, I am OpenDevin, an AI Software Engineer. What would you like me to build you today?` instead of one.

#### Setup and configuration
**Current version**:

```bash
fe736013cc861209bcfdfa61a4ff0d435e1fc3e2
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_API_KEY="pplx-redacted"
LLM_BASE_URL="https://api.perplexity.ai"
LLM_MODEL="perplexity/pplx-70b-chat"
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model: perplexity/pplx-70b-chat
* Agent: doesn't matter, happens on all

**Commands I ran to install and run OpenDevin**:
```
make build
make run
```

**Steps to Reproduce**:
1. Start the project
2. Open the UI and wait for the first introduction message
3. Change any settings (model, agent, workspace) from the UI and click Save

**Logs, error messages, and screenshots**:
![Screenshot 2024-04-02 at 10 03 27](https://github.com/OpenDevin/OpenDevin/assets/18368279/a89c5e0b-8617-49ae-be7b-d0abc3ac8d81)
