### ISSUE TITLE
Stuck in a loop using ollama/llama2

### ISSUE THREAD

**Issue by jab416171** [OpenDevin/OpenDevin#645]
#### Describe the bug

when I try to use OpenDevin, it just gets stuck in a loop and doesn't actually do anything.

#### Setup and configuration
**Current version**:

```bash
a9f469f0e736809699ce3a6c7513de05085ae9d4
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_API_KEY="11111111111111111111"
LLM_BASE_URL="http://localhost:11434"
LLM_MODEL= "ollama/llama2"
LLM_EMBEDDING_MODEL="llama2"
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model: llama2
* Agent: MonologueAgent

**Commands I ran to install and run OpenDevin**:
```
make build
make setup-config
make run
```

**Steps to Reproduce**:
1. install ollama and run OpenDevin with the above config

**Logs, error messages, and screenshots**:

![screenshot_20240403053022](https://github.com/OpenDevin/OpenDevin/assets/345752/4e881763-663e-47b8-96d1-00b237e017c3)
