### ISSUE TITLE
Denied pull docker image

### ISSUE THREAD

**Issue by arwahdevops** [OpenDevin/OpenDevin#688]
#### Describe the bug
```bash
Error response from daemon: Head "https://ghcr.io/v2/opendevin/sandbox/manifests/latest": denied: denied
```
**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_BASE_URL="http://localhost:1234/v1/"
LLM_API_KEY="lm-studio"
LLM_EMBEDDING_MODEL="local"
WORKSPACE_DIR="./workspace"
```

**Commands I ran to install and run OpenDevin**:
```
make build
```

**Logs, error messages, and screenshots**:
![image](https://github.com/OpenDevin/OpenDevin/assets/68539137/c6739362-1f57-44cd-a0b7-949e9b8a437d)
