### ISSUE TITLE
autopep8 and mypy are in conflict

### ISSUE THREAD

**Issue by iFurySt** [OpenDevin/OpenDevin#903]
<img width="1137" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/16201837/3a98fcb1-4309-432f-b963-3042d51bbece">

<img width="988" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/16201837/3b4a2abd-ed2a-47ec-a4fc-187a955dce59">

<img width="992" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/16201837/2f50011e-addd-4342-833e-a166697413da">

```
  - repo: https://github.com/hhatto/autopep8
    rev: v2.1.0
    hooks:
      - id: autopep8
```

autopep8 will auto-change files when i submit the commit, and the workflow will fail in the mypy stage.
