### ISSUE TITLE
Support/Document port configuration

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#954]
**What problem or use case are you trying to solve?**
Currently we hard code ports 3000, 3001, and 2222. Some users might need to listen on different ports.

**Describe the UX of the solution you'd like**
Probably env vars and/or `config.toml` for each port, and document somewhere

Related: can we stop Vite from searching for the closest available port, and instead fail if the port fails to bind?

**Comment by rbren** [comment]
This is pretty easy now, just using the `-p` option with docker run

**Comment by izogfif** [comment]
@rbren This no longer works it seems:
I created `docker-compose.yaml` that maps host port 3001 to container's port 3000:
```yaml
services:
  openhands-app:
    image: docker.openhands.dev/openhands/openhands:latest
    pull_policy: always
    ports:
      - "3001:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .openhands:/.openhands
    environment:
      - AGENT_SERVER_IMAGE_REPOSITORY=ghcr.io/openhands/agent-server
      - AGENT_SERVER_IMAGE_TAG=1.12.0-python
      - LOG_ALL_EVENTS=true
      - LOG_LEVEL=DEBUG
    extra_hosts:
      - "host.docker.internal:host-gateway"
```
I start new conversation and enter some sample question in the text field, e.g. "What is two times two?". I get "Failed to connect to server" message blinking above the text field, it cleans up and the "Changes" panel on the right reloads with "Protip". It seems that the "Failed to connect to server" message comes from the JavaScript part of openhands UI, because the container doesn't even try to contact LLM I specified in its settings. In "Plan" mode this just repeats infinitely.

If I map host port 3000 to container's port 3000 (and access the conversation via `http://localhost:3000/conversations/xxx`), everything seems to be working, but since port 3000 is already taken on my host by another application, I need a way to make openhands work on port 3001. And I'd like to do that without having to resort to some shady tricks like reverse proxy in front of openhands that rewrites ports in HTTP requests, redirects and other stuff.
